[project]
name = "rag-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dnspython>=2.8.0",
    "flask>=3.1.2",
    "kagglehub>=0.4.2",
    "langchain>=1.2.8",
    "langchain-text-splitters>=1.1.0",
    "pandas>=3.0.0",
    "pymongo>=4.16.0",
    "python-dotenv>=1.2.1",
    "voyageai>=0.3.7",
]
